export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_MEMBER = 'GET_CURRENT_MEMBER';
export const GET_CURRENT_MEMBER_SUCCESS = 'GET_CURRENT_MEMBER_SUCCESS';
